export interface QrGenerateRequest {
  /**
   * URL that the QR Experience will point to.
   */
  url: string;

  clicklink: string;

  /**
   * Accompanying text prompt that will decide the style or theme of the code.
   */
  prompt: string;

  /**
   * Conditioning scale for qr controlnet
   */
  qr_conditioning_scale?: number;

  /**
   * Steps to run denoising
   */
  num_inference_steps?: number;
}

export interface QrGenerateResponse {
  /**
   * URL of the QR Experience images that was generated by the model.
   */
  image_url: string;

  /**
   * Response latency in milliseconds.
   */
  model_latency_ms: number;
  
  componentType?: string; // componentType can be 'Body', 'BodyTok', or 'BodyImage'

  /**
   * Unique ID of the QR Experience.
   * This ID can be used to retrieve the QR Experience image from the API.
   */
  id: string;
}

export interface ImageGenerateRequest {
  /**
   * URL that the QR Experience will point to.
   */
  url: string;
  clicklink: string;
  /**
   * Accompanying text prompt that will decide the style or theme of the code.
   */
  prompt: string;

  width?: number;
  height?: number;
  guidance_scale?: number;
  negative_prompt?: string;
  pag_guidance_scale?: number;

  /**
   * Conditioning scale for qr controlnet
   */
  /**
   * Steps to run denoising
   */
  num_inference_steps?: number;
}

export interface ImageGenerateResponse {
  /**
   * URL of the QR Experience images that was generated by the model.
   */
  image_url: string;
  /**
   * Response latency in milliseconds.
   */
  model_latency_ms: number;
  
  componentType?: string; // componentType can be 'Body', 'BodyTok', or 'BodyImage'

  /**
   * Unique ID of the QR Experience.
   * This ID can be used to retrieve the QR Experience image from the API.
   */
  id: string;
}

export interface LogoGenerateRequest {
  /**
   * URL that the QR Experience will point to.
   */
  url: string;
  clicklink: string;
  /**
   * Accompanying text prompt that will decide the style or theme of the code.
   */
  prompt: string;

  size?: string;
  style?: string;
  
}

export interface LogoGenerateResponse {
  /**
   * URL of the QR Experience images that was generated by the model.
   */
  image_url: string;
  /**
   * Response latency in milliseconds.
   */
  model_latency_ms: number;
  
  componentType?: string; // componentType can be 'Body', 'BodyTok', or 'BodyImage'

  /**
   * Unique ID of the QR Experience.
   * This ID can be used to retrieve the QR Experience image from the API.
   */
  id: string;
}


export interface TokGenerateRequest {
  /**
   * URL that the QR Experience will point to.
   */
  url: string;
  clicklink: string;
  /**
   * Accompanying text prompt that will decide the style or theme of the code.
   */
  prompt: string;

  width?: number;
  height?: number;
  guidance_scale?: number;
  negative_prompt?: string;
  pag_guidance_scale?: number;
  

  /**
   * Conditioning scale for qr controlnet
   */
  /**
   * Steps to run denoising
   */
  num_inference_steps?: number;
}

export interface TokGenerateResponse {
  /**
   * URL of the QR Experience images that was generated by the model.
   */
  image_url: string;
  /**
   * Response latency in milliseconds.
   */
  model_latency_ms: number;
  
  componentType?: string; // componentType can be 'Body', 'BodyTok', or 'BodyImage'

  /**
   * Unique ID of the QR Experience.
   * This ID can be used to retrieve the QR Experience image from the API.
   */
  id: string;
}
